### PR TITLE
MM-231  Support config for which tab in sidebar is selected on map startup

### LINKED ISSUE #231: Support configuriation which tab is selected on map startup.
**Is your feature request related to a problem? Please describe.**
There is no way of specifying what tab is selected on startup within the side panel.

**Describe the solution you'd like**
Provide a method of configuring which tab is selected on map startup.

If no configuration setting present then default to Directory

**Describe alternatives you've considered**
None

**Acceptance Criteria**

- [ ] - Demonstrate it working on DotCoop where the Search panel is visible on startup.
- [ ] - Demonstrate it working on ICA with no config settings provided, so it should still default to Directory.
- [ ] - Demonstrate that it doesn't crash if it is set to a Datasets tab, when that tab is set to invisible.

### PR DESCRIPTION
**Pull request by rogup**
Closes #231

### CODE REVIEW

**Comment by wu-lee** [comment]
Experimenting with rebase and how it interacts with PRs.

I've:
- rebased the branch to the top of `dev`
- This has resulted in some commits being de-duplicated. In a minor difference between the branch commit f640d0d86c878bdcc and the one it reported being cherry-picked from, I infer the main branch one was the correct version (it lacked the `npm run build --if-present` command).
- I moved the `.prettierignore` commit to the top (this is not really part of the PR remit and at least warrants being separated - maybe it can live on master)
- I merged the two commits altering the config - "Add defaultPanel option to config" and the subsequentone, the first one with Prettier changes, and the second one reverting Prettier changes. This made the actual changes clear.
- I split out the stylistic changes from "Add defaultPanel option to config" into a prior commit, and followed through - removing all trailing semicolons.
- I also split the `desc:` field description corrections into a prior commit.

Pushing this back, beware, the branch will have moved. But this PR has adapted accordingly. Good.

**Comment by wu-lee** [comment]
I've added some typesafety - seems sensible and idiomatic in this case.  Tweaked and regenerated the docs accordingly. Everything appears to work as before, tests pass.

**Comment by wu-lee** [comment]
I think this is ready to merge? If @rogup you are ok with what I've done above?

**Comment by rogup** [comment]
@wu-lee thanks for making those changes. I think this is probably ready to merge, once I've tested it on the DotCoop and ICA maps

**Pull request merged**
